### ISSUE TITLE
A lot of odd crash with setupWAL

### ISSUE THREAD

**Issue by TonyTangAndroid** [commonsguy/cwac-saferoom#23]
I am not sure whether I should post the question here or not. I have used SafeRoom in my app. And it gets a lot of crashes after I bump the version from  0.3.4 to 0.4.1. For the record, 0.3.4 did not generate any crash like this. However, it could not be stably reproduced. It runs fine on my Pixel 2 device running 8.1. But based no Google Play crash report, it crashed on all kinds of kinds such as Galaxy J7 Prime (on7xelte) and Moto G Turbo Edition (merlin). It seems that the root cause is introduced by setupWAL.

```
SafeRoom Version : 0.4.1
Room Version : '1.1.1-rc1'
Sqlcipher : 3.5.9

```

> net.sqlcipher.database.SQLiteException: 
  at net.sqlcipher.database.SQLiteStatement.native_1x1_string (SQLiteStatement.java)
  at net.sqlcipher.database.SQLiteStatement.simpleQueryForString (SQLiteStatement.java)
  at com.commonsware.cwac.saferoom.Statement.simpleQueryForString (Statement.java)
  at com.commonsware.cwac.saferoom.Database.inTransaction (Database.java)
  or                     .simpleQueryForString (Database.java)
  at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWrappedDb (Helper.java)
  or                     .getWritableSupportDatabase (Helper.java)
  or                     .setupWAL (Helper.java)
  at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWrappedDb (Helper.java)
  or                     .getWritableSupportDatabase (Helper.java)
  or                     .setupWAL (Helper.java)
  at com.commonsware.cwac.saferoom.Helper$1.onUpgrade (Helper.java)
  at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java)
  at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWrappedDb (Helper.java)
  or                     .getWritableSupportDatabase (Helper.java)
  or                     .setupWAL (Helper.java)
  at com.commonsware.cwac.saferoom.Helper.getWritableDatabase (Helper.java)
  or                     .setWriteAheadLoggingEnabled (Helper.java)
  at android.arch.persistence.room.RoomDatabase.a (RoomDatabase.java)
  at android.arch.persistence.room.paging.LimitOffsetDataSource.d (LimitOffsetDataSource.java)
  at android.arch.persistence.room.paging.LimitOffsetDataSource.a (LimitOffsetDataSource.java)
  at android.arch.paging.PositionalDataSource.a (PositionalDataSource.java)
  at android.arch.paging.TiledPagedList.<init> (TiledPagedList.java)
  at android.arch.paging.PagedList.a (PagedList.java)
  at android.arch.paging.LivePagedListBuilder$1.b (LivePagedListBuilder.java)
  at android.arch.lifecycle.ComputableLiveData$2.run (ComputableLiveData.java)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  at java.lang.Thread.run (Thread.java:762)

**Comment by TonyTangAndroid** [comment]
No, unfortunately. The source of crash report comes from all supported Android API from 5.0 to 7.1.  This is the percentage of crash statistics grouped by Android version. 


Android 7.0 | 477 | 54.0%
-- | -- | --
Android 6.0 | 195 | 22.1%
Android 7.1 | 134 | 15.2%
Android 5.1 | 55 | 6.2%
Android 5.0 | 23 | 2.6%

And again, unfortunately, that's all the information that Google Play console collected. I am aware of 0.3.4 and Room 1.0.0 does not support WAL. I am to downgrade SafeRoom to 0.3.4

**Comment by TonyTangAndroid** [comment]
This is the crash statistics grouped by device model. 

Model | Crashed Times | Percentage
-- | -- | --
Galaxy J7 Prime (on7xelte) | 234 | 26.5%
Moto G Turbo Edition (merlin) | 49 | 5.5%
Redmi Note 4 (mido) | 41 | 4.6%
Eluga I3 (Eluga_I3) | 32 | 3.6%
Moto E4 (perry_f) | 23 | 2.6%
CPH1801 (CPH1801) | 23 | 2.6%
Galaxy J2(2016) (j2xlteins) | 21 | 2.4%
A1601 (A1601) | 20 | 2.3%
Galaxy S7 (heroqltevzw) | 20 | 2.3%
Mi A1 (tissot_sprout) | 19 | 2.1%
Galaxy S7 (herolte) | 17 | 1.9%
Moto C Plus (panell_d) | 17 | 1.9%
Galaxy J5 Prime (on5xelte) | 14 | 1.6%
Galaxy S6 Edge (zerolte) | 14 | 1.6%
LG K10 (2017) (mlv5n) | 13 | 1.5%
Galaxy Note3 (ha3g) | 13 | 1.5%
Galaxy J7(2016) (j7xelte) | 13 | 1.5%
Redmi 4 Pro (markw) | 13 | 1.5%
Galaxy J5(2016) (j5xnltelgt) | 13 | 1.5%
Mate 10 lite (HWRNE) | 12 | 1.4%

**Comment by commonsguy** [comment]
I don't own any of these devices, and I don't know how to reproduce the problem even if I had one. All I can tell from your stack trace is that you're using the Paging library, and it is the one attempting to get the database which is eventually triggering this crash.

I'll try getting a Galaxy J7 Prime and seeing if I can trigger the problem, but I'm not exactly hopeful.

If you get more information about the issue, please let me know.

**Comment by TonyTangAndroid** [comment]
I understand. Sure. I think I could get a Galaxy S6 Edge on hand tomorrow. I will try to reproduce it on that model tomorrow. Appreciate you making effort following up this issue.

**Comment by aleksandrp-hyuna** [comment]
@commonsguy I has a same problem. I created a [demo](https://github.com/aleksandrp-hyuna/SafeRoomMigration/) project to reproduce a problem.
`.setJournalMode(JournalMode.TRUNCATE)` fixes the crash, but the problem is still here.

**Comment by commonsguy** [comment]
@aleksandrp-hyuna That was very helpful -- many thanks!

This is giving me an actual error: `Caused by: net.sqlcipher.database.SQLiteException: error code 1: cannot change into wal mode from within a transaction`. I can also reproduce it on a Pixel running P DP3, FWIW. 

My guess is that this is also the problem seen by @TonyTangAndroid, as the stack trace is similar (despite not having the actual exception info). 

I understand the problem and will work to push out an update that fixes it within the next few days.

Thanks again!

**Comment by commonsguy** [comment]
OK, I understand a bit better what is going on, though other than documentation I am not certain that there is much that I can do about it.

The scenario that @aleksandrp-hyuna provided is crashing because the database already exists &mdash; created outside of Room and SafeRoom &mdash; and does not have WAL mode enabled. SafeRoom cannot take an existing non-WAL database and convert it to WAL, due to the way that `SQLiteOpenHelper` works, particularly on the upgrade path.

In the short term at least, the workaround is to enable WAL mode on the database, outside of Room/SafeRoom, before attempting to use Room/SafeRoom for the first time on the database. For example, in the demo app, calling `database.execSQL("PRAGMA journal_mode=WAL;");` after `database = helper.getWritableDatabase(PASSW);` clears up the problem... though it then crashes due to another bug in the demo (`private val MIGRATION_2_3 = object : Migration(3, 4)` needs to be `private val MIGRATION_2_3 = object : Migration(2, 3)`).

This might be a problem in Room itself, as much as it is with SafeRoom. I will do some more experiments on the weekend and will see what I can do to improve matters. But, in the meantime, executing `PRAGMA journal_mode=WAL;` on your existing database before trying to use it in Room/SafeRoom should help.

**Comment by aleksandrp-hyuna** [comment]
@commonsguy thanks a lot

**Comment by commonsguy** [comment]
OK, I created a test case based on the demo app provided by @aleksandrp-hyuna, and used that to implement a fix. v0.4.2 should clear up this problem.

Thanks to everyone for the help!
