### ISSUE TITLE
Make this project to use in production

### ISSUE THREAD

**Issue by silwar** [commonsguy/cwac-saferoom#26]
This project is good and can help me in my current app in a big way. Only problem with it is line written in description which says this project is for experimentation and should not be used in production. @commonsguy Can you provide tentative timeline till when this will be production ready?

**Comment by commonsguy** [comment]
I have no idea.

I will be less nervous about it after Zetetic ships the next major version of SQLCipher for Android. That should contain the APIs that I need to complete the `SupportSQLiteDatabase` implementation. Right now, a bunch of stuff is stubbed out, because the current SQLCipher for Android does not support it. It *happens* that the stubbed out stuff represents things that Room does not use presently, which is why SafeRoom is holding up as well as it is. However, I have no idea when Zetetic will ship that update.

If you have further questions, please use [the support options outlined in the documentation](https://github.com/commonsguy/cwac-saferoom#questions).

**Comment by silwar** [comment]
Thanks for info. 
and I will use support options for further questions for sure
