### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by hannesa2** [commonsguy/cwac-saferoom#29]
When I use `implementation "com.commonsware.cwac:saferoom.x:0.5.0"` I run into

> Warning: Exception while processing task java.io.IOException: Can't write [/Users/hannes/git/DBPrefs/sample/build/intermediates/transforms/proguard/debug/0.jar] (Can't read [/Users/hannes/.gradle/caches/transforms-1/files-1.1/saferoom.x-0.5.0.aar/4d39595e91b080982d88ecf1168b50ce/jars/classes.jar(;;;;;;;**.class)] (Duplicate jar entry [com/a/a/a/a.class]))
> Thread(Tasks limiter_2): destruction
> > Task :sample:transformClassesAndResourcesWithProguardForDebug FAILED

any ideas ?

**Comment by commonsguy** [comment]
I have no way of knowing what `com/a/a/a/a.class` refers to. If you can give me a project that reproduces the problem, I can attempt to research further, but just based on that message, I do not know how to proceed.

**Comment by hannesa2** [comment]
Thank you for coming back to me so quick !
It's this repo https://github.com/hannesa2/DbPreferences in branch `AndoidX`

**Comment by commonsguy** [comment]
You have this line in `samples/build.gradle`:

```
implementation 'com.commonsware.cwac:saferoom:0.4.4'
```

You do not need it. Partly, that is because you should be getting SafeRoom from DbPrefs. Partly, that is because you have a different version of that same dependency in DbPrefs. I changed the artifact ID (`saferoom.x` instead of `saferoom`), but I did not change the Java package for the classes, given that I don't really support two versions of SafeRoom in the same project at the same time.

So, get rid of that line, and `sample` builds. You might also get rid of any other dependencies in `sample` that you really should be getting from your `implementation project(':DBPrefs')` line.

BTW, to help diagnose this sort of thing, temporarily add `-dontobfuscate` to your `proguard-rules.pro` file, so the class name gets reported without obfuscation.
