### ISSUE TITLE
DB become read-only after decrypt 

### ISSUE THREAD

**Issue by alexkeong** [commonsguy/cwac-saferoom#31]
unable to write the DB after decryption.  I able to read the DB after decrypt but the DB becomes read-only when I tried to write data to a table.

SQLCipherUtils.decrypt(mcontext, mcontext.getDatabasePath(AppConstants.DB_NAME).getAbsoluteFile(),passwordInCharArray);

Here is the error message i get

    android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
    #################################################################
    Error Code : 1032 (SQLITE_READONLY_DBMOVED)
    Caused By : Database or Journal file have been removed.
    	(attempt to write a readonly database (code 1032))
    #################################################################

**Comment by commonsguy** [comment]
See [this test case](https://github.com/commonsguy/cwac-saferoom/blob/v0.5.0/saferoom/src/androidTest/java/com/commonsware/cwac/saferoom/test/DecryptTest.java) for how I am testing the current functionality.

In order to try to address your problem, I would need either:

- Details about what is different between your scenario and that test case, or
- A test case that can reproduce the problem, or
- A sample project that can reproduce the problem

Without any of those, I have nothing to go on in order to investigate what is causing your difficulty.

**Comment by alexkeong** [comment]
thanks for your quick response, I have fixed it by reopening the database.
