### ISSUE TITLE
cwac-saferoom. After Encryption,SQLCipherUtils.getDatabaseState Showing DOES_NOT_EXIST

### ISSUE THREAD

**Issue by gokulbalakrishnan** [commonsguy/cwac-saferoom#36]
cwac-saferoom Facing an issue when encrypt database, Once encrypt done. Next app launch

SQLCipherUtils.getDatabaseState(getDatabasePath(GeneralUtils.getDatabaseName()))

returning DOES_NOT_EXIST database state.

**Comment by indra452** [comment]
Try with / without ".db" extension

**Comment by gokulbalakrishnan** [comment]
yes i already not using .db extension

**Comment by indra452** [comment]
> yes i already not using .db extension

then try with .db

**Comment by gokulbalakrishnan** [comment]
net.sqlcipher.database.SQLiteException: database disk image is malformed safe room, When encrypting database

**Comment by commonsguy** [comment]
Quoting [the contribution guidelines](https://github.com/commonsguy/cwac-saferoom/blob/master/CONTRIBUTING.md#contributing-bug-reports), all bug reports need to include:

- the Android OS version on which you are experiencing the problem
-  the code necessary to reproduce the problem
- the steps necessary, using that code and that version of Android, to reproduce the problem

I have no means of helping you otherwise.

**Comment by gokulbalakrishnan** [comment]
ok will provide.

**Comment by commonsguy** [comment]
Closing as not reproducible. If you provide a way for me to reproduce your problem, I can reopen this issue.
