### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by qbait** [commonsguy/cwac-saferoom#42]
Hi Mark,
good job with the library. I'm choosing currently safe/encrypted persistence solution for a greenfield project and considering Room or Realm.
Do you have an idea when we can expect your lib to be production ready?

Thank you!

**Comment by commonsguy** [comment]
I really recommend using [other resources](https://github.com/commonsguy/cwac-saferoom#questions) for general questions.

I don't know how you wish to define "production ready". If you mean `1.0.0`, right now the library is [on `1.0.0-alpha3`](https://github.com/commonsguy/cwac-saferoom/blob/master/README-1.0.0.md). I have not received any bug reports about the 1.0.0 series yet. I expect that I will push out a `1.0.0-beta1` release in early January and `1.0.0` later in January, barring unforeseen problems.

**Comment by hannesa2** [comment]
I can not recommend it for production. The company, I work for, removed this lib <= `v1.0.1` because there was a lot of unexplainable, corrupted database (with stable password) observed in Crashlytics. 
Arrount 1 % of all sessions, it sounds not much, but when you have millions of installations, then it's too much !

We were never able to reproduce it in development, so we decided to remove it.

**Comment by filipesilvasword** [comment]
@hannesa2 If I may ask, what alternative to this library will your company implement or use?
My company hasn't really had any problems with this, though our user count is not as big.
Can you pinpoint a specific case or feature of this library that you use and that you think might be related to the corrupted databases? (even though you haven't been able to reproduce it)

Thanks in advance.

**Comment by JanFromTallence** [comment]
@hannesa2 Have you found an alternative library or is the only way to use SQLCipher directly? 
We have the same problem at our company, that every day 1-3 users have a crashed database. We actually use the old version 0.4.4 of Saferoom cause the 1.x.x are (really) slow on old devices, also if we use the Flag to use the old encryption of SQLCipher 3. The hope was, that version 1 of Saferoom will fix the problem, but it sounds it doesn't. How you mentioned it, the problem is not reproducable... Therefore the question again, is there an alternative?
