### ISSUE TITLE
SQLiteException when running SQLCipherUtils.encrypt()

### ISSUE THREAD

**Issue by bartek-wesolowski** [commonsguy/cwac-saferoom#62]
I wasn't able to reproduce the issue, but I'm seeing hundreds of crashes in Crashlytics with this exception when trying to migrate an existing database with `SQLCipherUtils.encrypt()`:
```
Caused by net.sqlcipher.database.SQLiteException: unable to close due to unfinalized statements or unfinished backups: sqlite3_close() failed
       at net.sqlcipher.database.SQLiteDatabase.dbclose(SQLiteDatabase.java)
       at net.sqlcipher.database.SQLiteDatabase.onAllReferencesReleased + 513(SQLiteDatabase.java:513)
       at net.sqlcipher.database.SQLiteDatabase.close + 1401(SQLiteDatabase.java:1401)
       at com.commonsware.cwac.saferoom.SQLCipherUtils.encrypt + 215(SQLCipherUtils.java:215)
       at com.commonsware.cwac.saferoom.SQLCipherUtils.encrypt + 152(SQLCipherUtils.java:152)
```

**Comment by commonsguy** [comment]
What version of SafeRoom are you using? And what is the specific `encrypt()` call that is triggering this exception?

**Comment by bartek-wesolowski** [comment]
I'm using SafeRoom 1.1.1 and using `public static void encrypt(Context ctxt, String dbName, byte[] passphrase)`

**Comment by commonsguy** [comment]
Sorry, I should have been more specific. Are you using `com.commonsware.cwac:saferoom.x:1.1.1` (the AndroidX edition) or `com.commonsware.cwac:saferoom:1.1.1` (the Android Support Library edition)?

**Comment by bartek-wesolowski** [comment]
It's `com.commonsware.cwac:saferoom.x:1.1.1`.

**Comment by commonsguy** [comment]
There are no background threads in [that version of `encrypt()`](https://github.com/commonsguy/cwac-saferoom/blob/v1.1.1/saferoom/src/main/java/com/commonsware/cwac/saferoom/SQLCipherUtils.java#L190-L223), so I have no idea what "unfinalized statements or unfinished backups" there might be. Similarly, I have no idea how I would wait for them to become finalized or finished.

Are there any commonalities among the devices that are reporting this crash? The only hope I have to address this is if I can reproduce it somehow.

**Comment by bartek-wesolowski** [comment]
I don't have access to the detailed data now, because I'm out of the office and I'll be back there on Monday, but as far as I can remember, there weren't any commonalities and the crash was happening on all Android versions from Lollipop to Pie and for many manufacturers (Samsung being leading the most crashes chart).

**Comment by commonsguy** [comment]
OK, I am seeing [if Zetetic recognizes that error](https://discuss.zetetic.net/t/sqliteexception-unable-to-close-due-to-unfinalized-statements-or-unfinished-backups/3818?u=commonsguy).

In the meantime:

- Make sure the database is closed before calling `encrypt()`, in case you are using the unencrypted database elsewhere
- Make sure you do not allow the user to get into a situation where they might trigger `encrypt()` twice

**Comment by bartek-wesolowski** [comment]
In my case encryption happens in `Application.onCreate()` when the database gets created by Koin, which is supposed to create a single instance of it. I'm pretty sure that I'm not using the original database earlier nor trying to encrypt it twice. I can triple check it later, but I haven't been able to replicate the exception myself so far.

I've done some code analysis and it seems that the exception is happening in `SQLCipherUtils` when trying to close the newly-created encrypted database that lives in a temporary file. Would having the original database open interrupt with closing that database? Wouldn't the exception happen later when trying to delete the original unencrypted database? Is it possible that the SQL statement that gets executed before closing the database doesn't get released properly? Even if I did try to run `encrypt()` twice at the same time, wouldn't the encrypted database be in two different temporary files and I would be able to run `db.close()` successfully on both of them?

We're seeing more problems with SafeRoom, although not as serious as this one. I haven't studied them much so far, so I haven't reported them, because they might be our fault, but they seem to follow a similar pattern where the log says that some database operation can't be executed because of some unreleased/not finalized resources. Our databases are usually singletons accessed through Room's DAOs.

**Comment by commonsguy** [comment]
> In my case encryption happens in Application.onCreate()

That's... an unexpected location to be using `encrypt()`. I expect that to be called when the user says "please encrypt this", either supplying a passphrase or having authenticated so you can use the AndroidKeyStore. I'm not saying that what you have is wrong, but it's definitely not what I had anticipated.

Do you have multiple processes in your app (i.e., `android:process` attribute on components in the manifest)?

> Would having the original database open interrupt with closing that database? Wouldn't the exception happen later when trying to delete the original unencrypted database? Is it possible that the SQL statement that gets executed before closing the database doesn't get released properly? Even if I did try to run encrypt() twice at the same time, wouldn't the encrypted database be in two different temporary files and I would be able to run db.close() successfully on both of them?

Sorry, I simply named some scenarios that I could think of that might explain why you are getting this exception when neither you nor I can reproduce it. If the variable is not OS version or device manufacturer, and the code works normally, there is something unusual about the situation where this is crashing. So, I brainstormed a couple of possibilities. The `android:process` question from above is another possibility.

Zetetic [suggests](https://discuss.zetetic.net/t/sqliteexception-unable-to-close-due-to-unfinalized-statements-or-unfinished-backups/3818/2?u=commonsguy) that I close that `SQLiteStatement` that I open to get the unencrypted database version. Since I'm already closing that database connection, I have difficulty believing that closing the statement will have an effect, but `¯\_(ツ)_/¯`. I'll make that change and push a new version this weekend.

> they seem to follow a similar pattern where the log says that some database operation can't be executed because of some unreleased/not finalized resources

It is possible that SQLCipher for Android is more sensitive to this than is the framework SQLite. SafeRoom mimics the `androidx.sqlite.framework` implementation. However, I have [a fairly decent test suite](https://gitlab.com/commonsguy/support-db-tests) and am not running into this, so it's either a scenario I have not tried or a situational thing. I'd need stack traces to have any hope of addressing them.

**Comment by commonsguy** [comment]
`com.commonsware.cwac:saferoom.x:1.1.2` closes the `SQLStatement` that I was not closing in `encrypt()` (also fixes a similar problem in `decrypt()`).

**Comment by bartek-wesolowski** [comment]
I'm not using `android:process`. I'm updating SafeRoom to the latest version. I also refactored the problematic class a little bit, so it doesn't create the database in `Application.onCreate()`, but only when the database is actually used. I'll let you know if this helps.

**Comment by bartek-wesolowski** [comment]
I'm not getting this exception anymore, so I guess this issue can be closed.

**Comment by commonsguy** [comment]
Glad to hear that things have improved!
