### ISSUE TITLE
libsqlcipher.so not generated for mips architecture

### ISSUE THREAD

**Issue by DeepanJN** [commonsguy/cwac-saferoom#69]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.my.project-ylDVYPJ077aLjRbuP05fyQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.my.project-ylDVYPJ077aLjRbuP05fyQ==/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libsqlcipher.so"

Crashed on the device: TCL 8082
OS version: Android 8.1.0
ABI:armeabi-v7a, armeabi

I have analyzed the apk and libsqlcipher.so is not found in MIPS lib.

But libsqlcipher.so have generated for these configurartions:
x86_64
x86
arm64-v8a
armeabi
armeabi-v7a

**Comment by commonsguy** [comment]
> I have analyzed the apk and libsqlcipher.so is not found in MIPS lib.

Zetetic does not distribute SQLCipher for Android for the MIPS architecture.

SafeRoom itself is not involved with native libraries for any architecture. SafeRoom depends upon SQLCipher for Android, and so your problem lies with with SQLCipher for Android. Zetetic offers [a support board for SQLCipher questions](https://discuss.zetetic.net/c/sqlcipher) &mdash; they may be able to give you some debugging advice there.

**Comment by DeepanJN** [comment]
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.charm.ehr.chartnote_india_android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.charm.ehr.chartnote_india_android-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libsqlcipher.so"

Device: Vivo X9
Os: Android 6.0.1

I am currently using "com.commonsware.cwac:saferoom:1.0.2"
Does arm64 and x86_64 are supported in this version?

Using abiFilters for arm64 and x86_64 will solve the problem or do you have any solution for it

**Comment by commonsguy** [comment]
> Does arm64 and x86_64 are supported in this version?

That is [a question for Zetetic](https://discuss.zetetic.net/c/sqlcipher). The native libraries are from SQLCipher, not SafeRoom.

> Using abiFilters for arm64 and x86_64 will solve the problem or do you have any solution for it

SafeRoom itself is not involved with native libraries for any architecture. SafeRoom depends upon SQLCipher for Android, and so your problem lies with with SQLCipher for Android. Zetetic offers [a support board for SQLCipher questions](https://discuss.zetetic.net/c/sqlcipher) — they may be able to give you some debugging advice there.
