### ISSUE TITLE
App crashes in release mode

### ISSUE THREAD

**Issue by ibrahimsalgin** [commonsguy/cwac-saferoom#70]
Hi,
Everything seems ok when I run my app in debug mode. However the app crashes whenever it is opened in release mode. Any idea?

**Comment by commonsguy** [comment]
I recommend that you examine the stack trace associated with your crash and use that information to try to identify what is going wrong. For example, you may need to adjust your ProGuard rules, as somebody else did in #22.

If you have further questions, please use [one of the support options that I list in the documentation](https://github.com/commonsguy/cwac-saferoom#questions). If you have evidence that the problem lies in the library, please follow [the project contribution guidelines for filing a bug report](https://github.com/commonsguy/cwac-saferoom/blob/master/CONTRIBUTING.md#contributing-bug-reports).
