### ISSUE TITLE
why the minSdkVersion is 15.

### ISSUE THREAD

**Issue by achenglike** [commonsguy/cwac-saferoom#8]
why the minSdkVersion is 15.

**Comment by commonsguy** [comment]
This is an issue tracker, not a support board. The project documentation lists [several support options](https://github.com/commonsguy/cwac-saferoom#questions). Please use them!

AFAIK, API Level 15 the `minSdkVersion` of Google's libraries, so I set this one to match, since I depend entirely upon a Google library.
